sillsdev/icu-dotnet

source/icu.net.sln, source/icu.net.tests/UnicodeSetTests.cs, source/icu.net.tests/icu.net.tests.csproj, source/icu.net/NativeMethods.cs, source/icu.net/UnicodeSet.cs, source/icu.net/icu.net.csproj
For the SIL WritingSystems LDML implementation, we needed access to ICU functions to convert between Unicode character sets and patterns
=> Add Unicode Set to convert between Set and Patterns

CHANGELOG.md, source/TestHelper/TestHelper.cs, source/icu.net.sln, source/icu.net.tests/NativeMethodsTests.cs, source/icu.net/IcuWrapper.cs, source/icu.net/NativeMethods.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/26)
=> Fix loading of native binary from directory with spaces in the path

source/icu.net/Boundary.cs, source/icu.net/ErrorCode.cs, source/icu.net/icu.net.csproj
This is my first pull request for icu-dotnet.  I might be able to submit more pull requests for the support of regular expressions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/28)
=> Fixed an XML comment bug by replacing < with &lt;.

CHANGELOG.md, source/TestHelper/TestHelper.cs, source/TestHelper/TestHelper.csproj, source/icu.net.sln, source/icu.net.tests/NativeMethodsTests.cs, source/icu.net.tests/icu.net.tests.csproj, source/icu.net.tests/packages.config, source/icu.net/NativeMethods.cs
We now check for the ICU binaries in x86/x64 subdirectories as well
as the directory where icu.net.dll lives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/31)
=> Support 64-bit versions of Icu4c

source/icu.net/NativeMethods.cs, source/icu.net/Properties/AssemblyInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/34)
=> Mark as assembly as CLSCompliant

source/icu.net.tests/Collation/RuleBasedCollatorTests.cs, source/icu.net/Collation/RuleBasedCollator.cs
Also improve its Dispose method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/40)
=> Dispose RuleBasedCollator in unit tests

build/icu-dotnet.proj, source/TestHelper/TestHelper.csproj, source/icu.net/NativeMethods.cs
PlatformTarget -> AnyCPU
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/38)
=> update TestHelper release configuration

source/icu.net/NativeMethods.cs, source/icu.net/RegexMatcher.cs, source/icu.net/icu.net.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/41)
=> Fix warnings and treat warnings as errors

source/icu.net.sln, source/icu.net.tests/NativeMethodsTests.cs, source/icu.net.tests/icu.net.tests.csproj, source/icu.net.tests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/42)
=> Update to newer icu4c packages

Jenkinsfile, source/icu.net/icu.net.csproj, source/icu.net/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/44)
=> Add Jenkinsfile for building

build/NuGet.targets, source/icu.net.tests/NativeMethodsTests.cs, source/icu.net.tests/icu.net.tests.csproj, source/icu.net.tests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/46)
=> Use ICU 58/59 for running unit tests

CHANGELOG.md, source/icu.net.tests/BreakIteratorTests.cs, source/icu.net/BreakIterators/BreakIterator.cs, source/icu.net/BreakIterators/RuleBasedBreakIterator.cs, source/icu.net/NativeMethods.cs, source/icu.net/icu.net.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/57)
=> Implement BreakIterator.Clone() (#56)

Jenkinsfile, build/TestBuild.sh, source/icu.net.tests/icu.net.tests.csproj, source/icu.net/icu.net.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/58)
=> Use msbuild to build on Linux

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/60)
=> Fix previous commit

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/61)
=> Trim whitespace from version number

CHANGELOG.md, source/icu.net.netstandard/NuGetAssets/icu.net.nuspec, source/icu.net/NativeMethods.cs, source/icu.net/Properties/AssemblyInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/64)
=>  Don't depend on libc6-dev package (#62)

CHANGELOG.md, README.md, source/icu.net/NativeMethods.cs
Also improve warning message if not initialized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/65)
=>  Update changelog and readme 

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/67)
=> Use pipeline library to define build job

CHANGELOG.md, source/icu.net/Character.cs, source/icu.net/NativeMethods.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/71)
=> Update comment and UProperty enum

source/icu.net/NativeMethods.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/83)
=> Add Tizen support

CHANGELOG.md, source/icu.net.tests/Normalization/Normalizer2Tests.cs, source/icu.net/Normalization/Normalizer.cs, source/icu.net/Normalization/Normalizer2.cs
Static methods in Normalizer class now simply call the Normalizer2
methods. Also add unit tests and show how normalization can be done
with the case folding tokenizer (#88).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/90)
=> Add Normalize() method to Normalizer2

CHANGELOG.md, source/icu.net/Character.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/91)
=> Add Character.IsLetter, .IsMark, and .IsSeparator methods

source/icu.net.tests/BreakIteratorTests.cs, source/icu.net.tests/LocaleTests.cs, source/icu.net.tests/MessageFormatterTests.cs, source/icu.net.tests/ResourceBundleTests.cs, source/icu.net.tests/TransliteratorTests.cs, source/icu.net.tests/UnicodeSetTests.cs, source/icu.net/Character.cs, source/icu.net/Collation/Collator.cs, source/icu.net/Locale.cs, source/icu.net/MessageFormatter.cs, source/icu.net/NativeMethods/NativeMethods.cs, source/icu.net/NativeMethods/NativeMethods_BreakIterator.cs, source/icu.net/NativeMethods/NativeMethods_CodepageConversion.cs, source/icu.net/NativeMethods/NativeMethods_Locales.cs, source/icu.net/NativeMethods/NativeMethods_MessageFormat.cs, source/icu.net/NativeMethods/NativeMethods_ResourceBundle.cs, source/icu.net/NativeMethods/NativeMethods_Transliterator.cs, source/icu.net/NativeMethods/NativeMethods_UnicodeSet.cs, source/icu.net/Normalization/Normalizer2.cs, source/icu.net/ResourceBundle.cs, source/icu.net/Transliterator.cs, source/icu.net/UnicodeSet.cs, source/icu.net/UnicodeString.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/92)
=> Fix signatures

CHANGELOG.md, source/icu.net.tests/BreakIteratorTests.cs, source/icu.net/BreakIterators/BreakEnumerator.cs, source/icu.net/BreakIterators/BreakIterator.cs, source/icu.net/BreakIterators/RuleBasedBreakIterator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/93)
=> Add BreakEnumerator class

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/96)
=> Release version 2.5

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/99)
=> Release version 2.5.1

source/icu.net/icu.net.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/101)
=> Update to newest SIL.ReleaseTasks

source/icu.net.tests/NativeMethodsTests.cs, source/icu.net/icu.net.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/103)
=> Debug test failure

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/105)
=> Release version 2.5.3

build/icu-dotnet.proj, source/icu.net.tests/icu.net.tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/114)
=> Upgrade NUnit.Console package

.github/FUNDING.yml
Adding this file will show a Sponsor button in GitHub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/113)
=> Add funding link

CHANGELOG.md, source/icu.net/icu.net.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/115)
=> Create nuget symbol package

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/116)
=> Update formatting of readme

LICENSE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/117)
=> Update license copyright year

CHANGELOG.md, source/icu.net.tests/BiDiTests.cs, source/icu.net/BiDi/BiDi.cs, source/icu.net/NativeMethods/NativeMethods.cs, source/icu.net/NativeMethods/NativeMethods_BiDi.cs
API and native methods for ICU's Unicode Bidirectional algorithm.
GitHub PR# 121.
+semver: minor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/123)
=> Add ICU Bidi support

CHANGELOG.md, source/icu.net/Collation/RuleBasedCollator.cs, source/icu.net/icu.net.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/124)
=>  Fix crash disposing RuleBasedCollator

CHANGELOG.md, GitVersion.yml
Also add company name, copyright, etc. to assembly info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/120)
=> Include build number in AssemblyFileVersion

Jenkinsfile, README.md, build/icu-dotnet.proj, source/icu.net.sln
This will help with archiving artifacts on AppVeyor.
=> Add default targets

README.md, source/icu.net/icu.net.csproj
Use `README.md` as nuget package readme.
=> Add package readme
