sillsdev/icu-dotnet

- source/icu.net.tests/BreakIteratorTests.cs
- source/icu.net/Boundary.cs
- source/icu.net/BreakIterator.cs
- source/icu.net/icu.net.csproj
The existing `BreakIterator.Split` method returns strings. This is a problem when you want use the returned string token within a larger piece of text because Windows and icu have different collation implementations.  This results in weird behaviour such as [dotnet/corefx#9202](https://github.com/dotnet/corefx/issues/9202).
This also adds the option to return non-categorized word boundaries such as punctuation and spaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/9)
> Add ability to get boundaries (for words and uncategorized words)

- source/icu.net/Character.cs
- source/icu.net/NativeMethods.cs
This allows the library to work with multiple ICU versions. This makes
it easier to produce a nuget package that works with any ICU version
(rather than having to create a separate package for each ICU version),
and it allows to use the same binary/nuget package for different
Linux versions which come pre-installed with different ICU versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/11)
> Dynamically load unmanaged ICU library

- source/icu.net/IcuWrapper.cs
- source/icu.net/NativeMethods.cs
This allows an application to select a specific (range of) ICU
version that the library attempts to load.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/12)
> Allow to limit considered ICU version

- source/icu.net.tests/Collation/CollatorTests.cs
- source/icu.net/Collation/RuleBasedCollator.cs
An ArgumentException is thrown when using .NET locale names because they use en-US as an identifier whereas, ICU uses en_US.  To fix this, canonize all given localeIds by creating a Locale object before passing it to Collator.Create method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/17)
> Support .NET Culture identifiers when using Collator

- source/icu.net.tests/Collation/RuleBasedCollatorTests.cs
- source/icu.net/Collation/Collator.cs
* Collator.GetCollationRules would return `null` because it was checking for `err != ErrorCode.NoErrors`. Modified to use `err.IsFailure()` like in BreakIterator
* Modified method to also take in a UColRuleOption if full rules are desired
* Added tests44
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/19)
> Fix Collator.GetCollationRules

- .gitattributes
- GitVersion.yml
- source/TestHelper/Properties/AssemblyInfo.cs
- source/TestHelper/TestHelper.cs
- source/TestHelper/TestHelper.csproj
- source/icu.net.sln
- source/icu.net.tests/NativeMethodsTests.cs
- source/icu.net.tests/icu.net.tests.csproj
- source/icu.net.tests/packages.config
- source/icu.net/NativeMethods.cs
If there are unmanaged ICU libraries in the same directory as icu.net.dll we will now use those even if we find a higher versioned ICU elsewhere on the path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/21)
> Prefer local directory when loading unmanaged ICU

- source/icu.net/Boundary.cs
- source/icu.net/BreakIterator.cs
- source/icu.net/Character.cs
- source/icu.net/Collation/AlternateHandling.cs
- source/icu.net/Collation/CaseFirst.cs
- source/icu.net/Collation/CaseLevel.cs
- source/icu.net/Collation/Collator.cs
- source/icu.net/Collation/FrenchCollation.cs
- source/icu.net/Collation/HiraganaQuaternary.cs
- source/icu.net/Collation/NormalizationMode.cs
- source/icu.net/Collation/NumericCollation.cs
- source/icu.net/Collation/RuleBasedCollator.cs
- source/icu.net/Collation/UColRuleOption.cs
- source/icu.net/ErrorCode.cs
- source/icu.net/IcuWrapper.cs
- source/icu.net/Locale.cs
- source/icu.net/Normalizer.cs
- source/icu.net/ParseError.cs
- source/icu.net/ParseErrorException.cs
- source/icu.net/RuleBasedBreakIterator.cs
- source/icu.net/UnicodeSet.cs
- source/icu.net/UnicodeString.cs
- source/icu.net/VersionInfo.cs
I recently pulled from master and I was getting around 280+ [CS1591 ](https://msdn.microsoft.com/en-us/library/zk18c1w9.aspx?f=255&MSPPError=-2147217396) warnings: "Missing XML comment for publicly visible type or member".  
This PR:
* Fixes all those warnings by adding documentation based on documentation in [ICU4C](http://icu-project.org/apiref/icu4c/)
* Adds [Obsolete] to properties/enum values that have values that are deprecated. (ie. [Collator.HiraganaQuaternary](https://github.com/sillsdev/icu-dotnet/compare/master...conniey:fixWarnings?expand=1#diff-4edbc99f1affddcfddc80262f12a09a6R49), [Character.BINARY_LIMIT](https://github.com/sillsdev/icu-dotnet/compare/master...conniey:fixWarnings?expand=1#diff-1326ee295886b5bf056871756b1c2281R243), etc.)
---
This change is [<img …
> Fix CS1591 warnings

- CHANGELOG.md
- source/icu.net/NativeMethods.cs
Look in lib/x86 and lib/x64 for ICU binaries in addition to
x86 and x64.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/39)
> Adjust to nuget3 compatible Icu4c packages

- source/icu.net.tests/NormalizerTests.cs
- source/icu.net/NativeMethods.cs
- source/icu.net/Normalizer.cs
This change also starts to use unorm2 methods instead of the deprecated
unorm* ones. The main change to fix the buffer overflow however is to
reset the errorcode variable (Mono bug?).
This fixes issue #47.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/49)
> Fix buffer overflow errors in Normalize()

- .gitignore
- CHANGELOG.md
- Jenkinsfile
- source/icu.net.tests/NativeMethodsTests.cs
- source/icu.net.tests/icu.net.tests.csproj
- source/icu.net.tests/packages.config
- source/icu.net/NativeMethods.cs
The newest versions of icu4c put the binaries in win-x64/win-x86 to
allow the use in a WIX installer. On Linux we look in linux-64/
linux-x86 instead. This change looks in these new directories
in addition to the locations we looked previously.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/52)
>  Check for ICU in new location (#51)

- CHANGELOG.md
- source/icu.net.tests/RegexMatcherTests.cs
- source/icu.net.tests/SetUpFixture.cs
- source/icu.net.tests/icu.net.tests.csproj
- source/icu.net/Collation/RuleBasedCollator.cs
- source/icu.net/IcuWrapper.cs
- source/icu.net/NativeMethods.cs
- source/icu.net/RegexMatcher.cs
This allows multi-threaded applications to initialize ICU before
starting multiple threads. The call to `Wrapper.Init()` should be the
first call of an ICU method.
See http://userguide.icu-project.org/design#TOC-ICU-Initialization-and-Termination.
+semver: minor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/55)
> Add `Wrapper.Init()` method (#54)

- CHANGELOG.md
- source/TestHelper/TestHelper.csproj
- source/icu.net.tests/icu.net.tests.csproj
- source/icu.net/icu.net.csproj
The PlatformTarget should be AnyCPU as it used to be until 2.3.2.
This allows it to run in both 32- and 64-bit processes. Somehow
the x86 target sneaked in for 2.3.3. This fixes issue #70.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/74)
> Fix targeting platform (#70)

- source/icu.net/icu.net.csproj
This allows to display the nuget package version as build
number in Jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/77)
> Save version number

- source/icu.net/icu.net.csproj
This will set the build number on Jenkins to `2.4.0-beta.14-75` instead of `2.4.0-beta0014-75`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/78)
> Use slightly more compact format for version number

- CHANGELOG.md
- source/icu.net.tests/NativeMethodsHelperTests.cs
- source/icu.net.tests/NativeMethodsTests.cs
- source/icu.net/NativeMethods.cs
- source/icu.net/NativeMethodsHelper.cs
Previously icu.net crashed if the filename on Linux contained a
minor version number, e.g. `libicuuc.so.60.1`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/85)
> Fix crash if filename contains minor version number

- CHANGELOG.md
- source/icu.net/NativeMethods.cs
If unmanaged libraries can't be loaded we now output the error
message from the OS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/86)
> Output error message on Linux

- CHANGELOG.md
- source/icu.net.tests/IcuWrapperTests.cs
- source/icu.net.tests/NativeMethodsHelperTests.cs
- source/icu.net.tests/NativeMethodsTests.cs
- source/icu.net/IcuWrapper.cs
- source/icu.net/NativeMethods/NativeMethods.cs
- source/icu.net/NativeMethods/NativeMethodsHelper.cs
Also add Wrapper.MinSupportedIcuVersion and
Wrapper.MaxSupportedIcuVersion constants.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/94)
> Allow to confine version number after initialization

- CHANGELOG.md
- source/icu.net/icu.net.csproj
This fixes the wrong version number for netstandard1.6 assembly (issue #72).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/95)
>  Update GitVersion dependency to 4.0.0

- CHANGELOG.md
- source/icu.net/Collation/RuleBasedCollator.cs
The `SafeHandle` base class calls `ReleaseHandle()`, so there is
no need to override `Dispose(bool)` and call it again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/104)
> Remove double call of dispose when disposing `RuleBasedCollator`

- source/icu.net.tests/TimeZoneTests.cs
- source/icu.net/NativeMethods/NativeMethods_TimeZone.cs
- source/icu.net/Timezone/Timezone.cs
- source/icu.net/Timezone/USystemTimeZoneType.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/108)
> Add TimeZone class

- source/icu.net.tests/Collation/CollatorTests.cs
These tests show the behavior when a predefined collator isn't
available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/112)
> Add some collator tests

- source/icu.net/BreakIterators/RuleBasedBreakIterator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/128)
> Fix for #127 BreakIterator.GetBoundaries is exponentially slow depending on the size of the source text

- CHANGELOG.md
- source/icu.net/IcuWrapper.cs
- source/icu.net/NativeMethods/NativeMethods.cs
Setting Icu.Wrapper.Verbose to `true` outputs additional information that might help in diagnosing loading the unmanaged icu library.
+semver:minor
> Add Icu.Wrapper.Verbose property

- source/Directory.Build.targets
- source/icu.net.tests/Normalization/Normalizer2Tests.cs
- source/icu.net/Normalization/Normalizer2.cs
Cast the return type to byte to match the C++ API.
This prevents corrupting the return value with leading bits.
Fixes #139 and https://jira.sil.org/browse/LT-20408
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/icu-dotnet/140)
> Fix return type of GetCombiningClass

- CHANGELOG.md
- source/icu.net/App.config
- source/icu.net/NativeMethods/NativeMethods.cs
> Add Mac support for library loading

- README.md
Add instructions needed for running `icu.net` >= 2.7.1 within Docker.
> Add instructions for Docker

- appveyor.yml
The `cmd: >-` concatenates lines if there are no empty lines in-between, so this change should fix this.
> Fix appveyor environment setting

- source/icu.net.tests/BreakIteratorTests.cs
- source/icu.net/NativeMethods/NativeMethods_BreakIterator.cs
The locale string must be passed as UnmanagedType.LPStr, as opposed to the actual text, which must be passed as Unicode string.
Otherwise, only the first character of the locale string is used.
An example, for which the locale actually matters, is added as test.
> Fix passing locale to ubrk_open

- CHANGELOG.md
- source/icu.net.tests/UnicodeSetTests.cs
- source/icu.net/UnicodeSet.cs
We were casting the Unicode code point into a char. Now we
use char.ConvertFromUtf32().
https://jira.sil.org/browse/LT-21010
> LT-21010: ToCharacters() fix bug with upper Unicode planes

- CHANGELOG.md
- source/icu.net.tests/IcuWrapperTests.cs
- source/icu.net/IcuWrapper.cs
- source/icu.net/NativeMethods/NativeMethods.cs
If you want to continue to use ICU after calling u_cleanup you'll have to call u_init first!
This fixes #174.
> Don't call any ICU methods after calling `u_cleanup`

- .github/workflows/CI-CD.yml
This should fix warning about deprecated Node.js 16.
> Update GHA actions

- source/icu.net/NativeMethods/NativeMethods.cs
- source/icu.net/Platform.cs
In `Platform.cs`, enable distinguishing MacOSX from Unix on all of .NET Core and Standard, not just .NET Standard 1.6.
In `NativeMethods.cs` > `CheckDirectoryForIcuBinaries`, compute library name length.
In `NativeMethods.cs` > `LocateIcuLibrary`, add `osx` and expand options.
> Expand Mac support

- .github/workflows/CI-CD.yml
- source/Directory.Build.props
- source/TestHelper/TestHelper.csproj
- source/icu.net.tests/IcuWrapperTests.cs
- source/icu.net.tests/NativeMethods/NativeMethodsHelperTests.cs
- source/icu.net.tests/NativeMethods/NativeMethodsTests.cs
- source/icu.net.tests/ResourceBundleTests.cs
- source/icu.net.tests/TimeZoneTests.cs
- source/icu.net.tests/icu.net.tests.csproj
- source/icu.net/NativeMethods/NativeMethodsHelper.cs
- source/icu.net/icu.net.csproj
This resolves a number of problems with using icu-dotnet on macOS. It helps with a number of issues found in https://github.com/paranext/paranext-core/issues/264.
This change adds macOS to the github builds so that future breaks should be caught by normal CI/CD workflows.
> Fix builds on macOS

- source/icu.net/NativeMethods/NativeMethods.cs
When publishing a Single file application we would get an error when trying to initlize Icu. This PR fixes that issue.
To test run the following in the TestHelper project
```bash
dotnet publish -r win-x64 --property:PublishSingleFile=true --framework net8.0
```
the resulting exe can be found in `icu-dotnet\output\Release\TestHelper\net8.0\win-x64\publish`, copy in the native ICU dlls to that folder and run that with the following (numbers being the icu version range)
```bash
.\TestHelper.exe 70 72
```
before this PR you would get this exception:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Icu.NativeMethods' threw an exception.
---> System.UriFormatException: Invalid URI: The URI is empty.
at System.Uri.CreateThis(String uri, Boolean dontEscape, …
```
> fix invalid Uri error when running in a Single file application

- source/icu.net/NativeMethods/NativeMethods.cs
On macOS the only way to get detailed error information about library loading is through the exception message. According to the `man` page for `dlopen`, the way to get detailed error information is through calling `dlerror`. We can't do that directly in .NET on macOS because the `libdl` doesn't exist anymore. So .NET has to do it for us under the covers and pass the results through the exception message. We've been throwing that away.
This isn't an urgent fix by any means, but it is something we should include in our logging.
> Log exception messages on .NET 6+ when dynamic library loading fails

- .github/workflows/CI-CD.yml
- .github/workflows/codeql.yml
- .github/workflows/test-results.yml
Recently `ubuntu-latest` switched from `ubuntu-22.04` to `ubuntu-24.04`, causing the CI-CD build checks to start failing.
> Pin GHA checks to ubuntu-22.04

- .github/workflows/CI-CD.yml
It's no longer available: https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/ & https://github.com/actions/runner-images/issues/10721
> Drop macos-12 from CI-CD workflow
